### ISSUE TITLE
Rename old variable names

### ISSUE THREAD

**Issue by marceline-cramer** [mondradiko/canary#16]
Many variable/parameter names still have the `ui_` prefix from before this repository was officially named Canary. This can be abbreviated, i.e. from `ui_script` to just `script` and from `ui_panel` to just `panel`.

**Comment by Zkarvx** [comment]
Hi @marceline-cramer ,
if you don't mind i would like to rename old variable.
i have one doubt in src/draw_list.c  line no. 34 `new_ui_draw` do i have to change it also to `new_draw` or only `ui_` prefix i have to change.

**Comment by marceline-cramer** [comment]
@Zkarvx Thank you for asking, I should add that `ui_draw` variables/params should be renamed to `draw_list`, and `new_ui_draw` can also be renamed to `new_draw_list`.

**Comment by Zkarvx** [comment]
@marceline-cramer so any `new_ui_xxx` should be `new_xxx_list` because i find `new_ui_panel`.

**Comment by marceline-cramer** [comment]
@Zkarvx `new_ui_panel` should be renamed `new_panel`.

**Comment by Zkarvx** [comment]
@marceline-cramer okay then `new_ui_script` should be `new_script`

**Comment by marceline-cramer** [comment]
@Zkarvx Exactly.
